from __future__ import annotations

import os
import re
import tempfile
from datetime import datetime
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path

import yaml

from ..discovery.models import LogicalModule
from ..settings import AriadneConfig
from .models import GenerationError, PlannedModule
from .planning import module_id, slug


class ValidationError(GenerationError):
    pass


class PersistenceError(GenerationError):
    pass


def compose_document(
    draft: str,
    *,
    config: AriadneConfig,
    module: LogicalModule,
    generated_at: datetime,
    source_commit_value: str | None,
    model: str,
    has_api: bool = False,
    document_type: str = "module",
) -> str:
    body = draft.strip()
    timestamp = generated_at.isoformat()
    commit_text = (
        f" from source commit `{source_commit_value}`" if source_commit_value else ""
    )
    disclaimer = (
        f"*This AI-generated documentation was generated by Ariadne on "
        f"{generated_at.date().isoformat()}{commit_text}. If a human maintainer "
        "modifies or reviews this document, please record that change in the "
        "provenance metadata or review notes.*"
    )
    metadata = {
        "ariadne": {
            "generated": True,
            "generated_at": timestamp,
            "tool_version": tool_version(),
            "model": model,
            "source_commit": source_commit_value,
            "logical_module": module.physical_path,
            "status": "AI-GENERATED",
            "human_reviewed": False,
            "human_modified": False,
            "api": has_api,
            "document_type": document_type,
        }
    }
    yaml_text = yaml.safe_dump(metadata, sort_keys=False).strip()
    parts = [f"---\n{yaml_text}\n---"]
    parts.extend([disclaimer, body])
    return "\n\n".join(parts) + "\n"


def compose_openapi_document(
    draft: str,
    *,
    module: LogicalModule,
    generated_at: datetime,
    source_commit_value: str | None,
    model: str,
) -> str:
    """Normalize a model response and attach OpenAPI-compatible provenance."""
    body = draft.strip()
    fenced = re.fullmatch(r"```(?:ya?ml|json)?\s*\n(.*)\n```", body, re.DOTALL)
    if fenced:
        body = fenced.group(1)
    try:
        parsed = yaml.safe_load(body)
    except yaml.YAMLError as exc:
        raise ValidationError("generated OpenAPI document is invalid YAML") from exc
    if not isinstance(parsed, dict):
        raise ValidationError("generated OpenAPI document must be a mapping")
    parsed["x-ariadne"] = {
        "generated": True,
        "generated_at": generated_at.isoformat(),
        "tool_version": tool_version(),
        "model": model,
        "source_commit": source_commit_value,
        "logical_module": module.physical_path,
        "status": "AI-GENERATED",
        "human_reviewed": False,
        "human_modified": False,
        "document_type": "openapi",
    }
    return yaml.safe_dump(parsed, sort_keys=False, allow_unicode=True)


_API_MARKER = re.compile(
    r"^\s*<!--\s*ariadne-api:\s*(true|false)\s*-->\s*", re.IGNORECASE
)


def extract_api_assessment(draft: str) -> tuple[str, bool]:
    """Remove the harness-only API marker and return its boolean assessment."""
    match = _API_MARKER.match(draft)
    if match is None:
        return draft, False
    return draft[match.end():], match.group(1).casefold() == "true"


def validate_document(document: str) -> None:
    if not document.strip():
        raise ValidationError("generated document is empty")
    remainder = document
    metadata: dict[str, object] = {}
    if document.startswith("---\n"):
        end = document.find("\n---\n", 4)
        if end < 0:
            raise ValidationError("front matter is not terminated")
        try:
            parsed = yaml.safe_load(document[4:end]) or {}
        except yaml.YAMLError as exc:
            raise ValidationError("front matter is invalid YAML") from exc
        if not isinstance(parsed, dict):
            raise ValidationError("front matter must be a mapping")
        metadata = parsed
        remainder = document[end + 5 :]
    else:
        raise ValidationError("front matter is missing")
    provenance = metadata.get("ariadne")
    if not isinstance(provenance, dict) or not all(
        key in provenance
        for key in {
            "generated", "generated_at", "tool_version", "model",
            "logical_module", "status", "human_reviewed",
        }
    ):
        raise ValidationError("front matter provenance is incomplete")
    if "AI-generated documentation" not in remainder:
        raise ValidationError("AI-generated disclaimer is missing")
    if re.search(
        r'(?i)(<tool_call\b|["\']tool_calls["\']\s*:|'
        r'["\']tool_call_id["\']\s*:)',
        remainder,
    ):
        raise ValidationError("document contains tool protocol data")
    titles = re.findall(r"^# (.+)$", remainder, flags=re.MULTILINE)
    if len(titles) != 1 or not titles[0].strip():
        raise ValidationError("document must contain exactly one level-one title")


def validate_openapi_document(document: str) -> None:
    try:
        spec = yaml.safe_load(document)
    except yaml.YAMLError as exc:
        raise ValidationError("generated OpenAPI document is invalid YAML") from exc
    if not isinstance(spec, dict):
        raise ValidationError("generated OpenAPI document must be a mapping")
    version = spec.get("openapi")
    if not isinstance(version, str) or not version.startswith("3."):
        raise ValidationError("OpenAPI document requires an OpenAPI 3.x version")
    info = spec.get("info")
    if not isinstance(info, dict):
        raise ValidationError("OpenAPI document requires an info object")
    for key in ("title", "version"):
        if not isinstance(info.get(key), str) or not info[key].strip():
            raise ValidationError(f"OpenAPI info requires a non-empty {key}")
    paths = spec.get("paths")
    if not isinstance(paths, dict) or not paths:
        raise ValidationError("OpenAPI document requires a non-empty paths object")
    operations = {"get", "put", "post", "delete", "options", "head", "patch", "trace"}
    for path, path_item in paths.items():
        if not isinstance(path, str) or not path.startswith("/"):
            raise ValidationError("OpenAPI path keys must begin with /")
        if not isinstance(path_item, dict):
            raise ValidationError(f"OpenAPI path item {path} must be an object")
        for method, operation in path_item.items():
            if method.casefold() not in operations:
                continue
            if not isinstance(operation, dict):
                raise ValidationError(
                    f"OpenAPI operation {method.upper()} {path} must be an object"
                )
            responses = operation.get("responses")
            if not isinstance(responses, dict) or not responses:
                raise ValidationError(
                    f"OpenAPI operation {method.upper()} {path} requires responses"
                )
            for status, response in responses.items():
                if not isinstance(status, (str, int)):
                    raise ValidationError(
                        "OpenAPI response keys must be status codes or default"
                    )
                if not isinstance(response, dict) or not (
                    isinstance(response.get("description"), str)
                    and response["description"].strip()
                    or isinstance(response.get("$ref"), str)
                ):
                    raise ValidationError(
                        f"OpenAPI response {status} for {method.upper()} {path} "
                        "requires a description or $ref"
                    )
    provenance = spec.get("x-ariadne")
    if not isinstance(provenance, dict) or provenance.get("generated") is not True:
        raise ValidationError("OpenAPI provenance is missing")


def validate_test_file(content: str) -> None:
    if not content.strip():
        raise ValidationError("generated test file is empty")
    if re.search(r"^```", content, flags=re.MULTILINE):
        raise ValidationError("generated test file contains Markdown fences")
    if re.search(
        r'(?i)(<tool_call\b|["\']tool_calls["\']\s*:|'
        r'["\']tool_call_id["\']\s*:)',
        content,
    ):
        raise ValidationError("generated test file contains tool protocol data")


def persist_new_test(destination: Path, content: str) -> None:
    """Atomically create a test without ever replacing an existing file."""
    destination.parent.mkdir(parents=True, exist_ok=True)
    if destination.exists():
        raise PersistenceError(f"refusing to overwrite existing test file: {destination}")
    temporary: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            newline="\n",
            dir=destination.parent,
            prefix=f".{destination.name}.",
            suffix=".tmp",
            delete=False,
        ) as handle:
            handle.write(content.rstrip() + "\n")
            handle.flush()
            os.fsync(handle.fileno())
            temporary = Path(handle.name)
        os.link(temporary, destination)
        temporary.unlink()
    except FileExistsError as exc:
        if temporary is not None:
            temporary.unlink(missing_ok=True)
        raise PersistenceError(
            f"refusing to overwrite existing test file: {destination}"
        ) from exc
    except OSError as exc:
        if temporary is not None:
            temporary.unlink(missing_ok=True)
        raise PersistenceError(f"cannot persist generated test: {destination}") from exc


def persist_document(
    destination: Path,
    document: str,
    *,
    config: AriadneConfig,
    force: bool = False,
) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    if destination.exists():
        metadata = read_document_metadata(destination)
        provenance = metadata.get("ariadne", {})
        if not isinstance(provenance, dict):
            provenance = {}
        human_changed = bool(
            provenance.get("human_reviewed") or provenance.get("human_modified")
        )
        generated = provenance.get("generated") is True
        if human_changed and not (force or config.generation.overwrite_human_modified):
            raise PersistenceError(f"refusing to overwrite human-modified document: {destination}")
        if not generated and not force:
            raise PersistenceError(f"refusing to overwrite non-Ariadne document: {destination}")
        if generated and not config.generation.overwrite_generated and not force:
            raise PersistenceError(f"generated document already exists: {destination}")
    try:
        _atomic_write(destination, document)
    except OSError as exc:
        raise PersistenceError(
            f"cannot persist documentation: {destination}"
        ) from exc


def persist_partial_draft(
    root: Path,
    run_id: str,
    plan: PlannedModule,
    text: str,
    model: str,
    generated_at: datetime,
    *,
    document_type: str = "module",
) -> Path:
    destination = (
        root
        / ".ariadne"
        / "drafts"
        / run_id
        / (
            f"{slug(plan.module.physical_path)}-"
            f"{module_id(root, plan)[:8]}.md"
        )
    )
    metadata = {
        "ariadne": {
            "generated": True,
            "draft": True,
            "generated_at": generated_at.isoformat(),
            "tool_version": tool_version(),
            "model": model,
            "logical_module": plan.module.physical_path,
            "status": "PARTIAL",
            "human_reviewed": False,
            "human_modified": False,
            "document_type": document_type,
        }
    }
    document = (
        "---\n"
        f"{yaml.safe_dump(metadata, sort_keys=False).strip()}\n"
        "---\n\n"
        f"{text.strip()}\n"
    )
    destination.parent.mkdir(parents=True, exist_ok=True)
    try:
        _atomic_write(destination, document)
    except OSError as exc:
        raise PersistenceError(f"cannot persist partial draft: {destination}") from exc
    return destination


def read_document_metadata(path: Path) -> dict[str, object]:
    try:
        text = path.read_text(encoding="utf-8")
        if path.suffix.casefold() in {".yaml", ".yml", ".json"}:
            parsed = yaml.safe_load(text)
            if isinstance(parsed, dict) and isinstance(parsed.get("x-ariadne"), dict):
                return {"ariadne": parsed["x-ariadne"]}
            return {}
        if not text.startswith("---\n"):
            return {}
        end = text.find("\n---\n", 4)
        parsed = yaml.safe_load(text[4:end]) if end >= 0 else {}
        return parsed if isinstance(parsed, dict) else {}
    except (OSError, UnicodeError, yaml.YAMLError):
        return {}


def is_markdown_like(text: str) -> bool:
    return bool(re.search(r"^# \S.*$", text, flags=re.MULTILINE))


def tool_version() -> str:
    try:
        return version("ariadne")
    except PackageNotFoundError:
        return "0.1.0"


def _atomic_write(destination: Path, content: str) -> None:
    temporary: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            newline="\n",
            dir=destination.parent,
            prefix=f".{destination.name}.",
            suffix=".tmp",
            delete=False,
        ) as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
            temporary = Path(handle.name)
        os.replace(temporary, destination)
    except OSError:
        if temporary is not None:
            temporary.unlink(missing_ok=True)
        raise
